[package]
name = "blackscholes"
version = "0.17.3"
edition = "2021"
license = "MIT"
description = "Black-Scholes option pricing model calculator"
repository = "https://github.com/hayden4r4/blackscholes-rust"
documentation = "https://docs.rs/blackscholes"
readme = "README.md"
authors = ["Hayden Rose"]
keywords = ["finance", "option", "pricing", "blackscholes", "option-pricing"]

[dependencies]
num-traits = "0.2.15"
statrs = "0.16.0"