[package]
name = "blackscholes"
version = "0.22.2"
edition = "2021"
license = "MIT"
description = "Black-Scholes option pricing model calculator"
repository = "https://github.com/hayden4r4/blackscholes-rust"
documentation = "https://docs.rs/blackscholes"
readme = "README.md"
authors = ["Hayden Rose"]
keywords = ["finance", "option", "pricing", "blackscholes", "option-pricing"]

[[bench]]
name = "pricing"
harness = false

[build-dependencies]
cc = { version="1.0", features=["parallel"] }

[dev-dependencies]
criterion = "0.4.0"

[dependencies]
num-traits = "0.2.15"
statrs = "0.16.0"
libc = "0.2"
