name: Benchmark

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'benches/**'
      - 'Cargo.*'
      - '.github/workflows/benchmark.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'benches/**'
      - 'Cargo.*'
      - '.github/workflows/benchmark.yml'
  schedule:
    - cron: '0 2 * * *'  # Daily at 02:00 UTC for baseline data

# Prevent concurrent benchmark runs that could interfere with gh-pages updates
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-22.04  # Pinned for reproducibility
    
    # Minimal permissions for security
    permissions:
      contents: write        # Allow gh-pages push
      pull-requests: write   # Allow PR commenting
      deployments: write     # Allow GitHub Pages deployment
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@nightly
      
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "bench-${{ runner.os }}"
      
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gnuplot
          cargo install cargo-criterion

      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
