name: Rust

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          "wasm32-unknown-unknown",
          "aarch64-unknown-linux-gnu",
          "x86_64-unknown-linux-gnu",
          "x86_64-pc-windows-gnu" ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Install target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }} --verbose

  fmt_clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Fmt
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --verbose

  tests:
    runs-on: ubuntu-latest
    needs: fmt_clippy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Tests
        run: cargo test --all-targets --verbose

  security_audit:
    runs-on: ubuntu-latest
    needs: fmt_clippy
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run cargo-audit
        run: cargo audit

  coverage:
    runs-on: ubuntu-latest
    needs: [ tests, security_audit ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
# TODO: Doesn't work @hayden4r4
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        files: lcov.info
#        fail_ci_if_error: true